analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.45498
title: Garden Gnewb
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.25
  brandStrength: 0.1875
  rhythmicContrast: 0.75
  brandColors:
    - '#3e424e'
    - '#fdfeff'
    - '#c0bbbf'
    - '#80879a'
    - '#d1ea69'
  lightness: 0.4375
purpose: []
favicon: null
name: Garden Newb
typography_spectrum: 0.41661
